# -*- coding: utf-8 -*-
"""yamil_cafe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJh6juWVsSlsNNOt2aK8EsGv-6Mo6_J-
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# #importar las libreiras
# import streamlit as st
# from PIL import Image
# from pymongo import MongoClient
# from bson.objectid import ObjectId
# import pandas as pd
# from datetime import datetime
# 
# #conexion a la base de mongohs
# import pymongo
# 
# URI= "mongodb+srv://wilbur_soot_lover:wilbur_uwu@clusteruwu.yoorukt.mongodb.net/?appName=Clusteruwu"
# 
# clienten = pymongo.MongoClient(URI)
# try:
#   clienten.server_info()
#   print("conexion exitosa :p")
# except Exception as e:
#   print("error :c",e)
# 
# db = clienten["yamil_cafes"]
# menu = db["menu"]
# gatos = db["gato"]
# clientes = db["cliente"]
# 
# #Configuracion de la interfaz del menu
# 
# st.set_page_config(page_title="✮⋆˙yamils_cafe_online", layout="wide")
# 
# st.image("yamil_logo.png",width=650 )
# 
# 
# st.title("⋆.˚✮_administracion_✮˚.⋆")
# st.markdown("⋆.˚✮_Esta area es la administracion del menu_✮˚.⋆")
# 
# # Crear todas las pestañas en una sola fila
# tab_ver_menu, tab_agregar_menu, tab_editar_menu, tab_eliminar_menu, \
# tab_ver_gatos, tab_agregar_gatos, \
# tab_rankig_clientes, tab_editar_cliente, tab_agregar_cliente = st.tabs([
#     "✮-Ver Productos del menu˙",
#     "✮-agregar al menu-",
#     "✮-editar menu-✮⋆˙",
#     "✮-eliminar del menu-✮",
#     "✮-Ver gatos-✮",
#     "✮-agregar nuevo gato",
#     "✮-Ver ranking de clientes",
#     "✮-editar cliente",
#     "✮-agregar nuevo cliente"
# 
# ])
# 
# with tab_ver_menu:
# 
#     st.image("ver_m.png",width=500 )
# 
#     st.markdown("⋆.˚✮_Esta area es la visualisacion del menu_✮˚.⋆")
#     st.header("Listado de Productos Actuales")
#     # Obtener documentos actualizados
#     documentos = list(menu.find())
# 
#     if documentos:
#       t_menu = len(documentos)
#       stock_menu = sum(doc.get('stock', 0) for doc in documentos)
#       precios = [doc.get('precio', 0) for doc in documentos]
#       precio_t = sum(precios) / t_menu if t_menu > 0 else 0
# 
#       col_m1, col_m2, col_m3 = st.columns(3)
# 
#       col_m1.metric("Total de Productos", t_menu)
#       col_m2.metric("Stock Total", int(stock_menu))
#       col_m3.metric("Precio promedio",f"${precio_t:.2f}")
# 
# 
#     # --- DISEÑO DE LA TABLA CON ACCIONES ---
# 
#       proporciones = [0.6, 1.5, 0.8, 0.8, 1, 1.5, 1.5, 0.9, 1, 0.5]
# 
# 
#     # Encabezados de la tabla
# 
#       cols_header = st.columns(proporciones)
#       cols_header[0].markdown("*id*")
#       cols_header[1].markdown("*nombre*")
#       cols_header[2].markdown("*precio*")
#       cols_header[3].markdown("*stock*")
#       cols_header[4].markdown("*categoria*")
#       cols_header[5].markdown("*descripcion*")
#       cols_header[6].markdown("*ingredientes*")
#       cols_header[7].markdown("*estado*")
#       cols_header[8].markdown("*sellos*")
#       st.markdown("<hr style='margin-top:0px; margin-bottom:10px;'>", unsafe_allow_html=True)
# 
#     # Renderizar cada documento como una fila de la tabla
#       for index,doc in enumerate(documentos,start=1):
#         cols_row = st.columns(proporciones)
#         # Datos de las celdas
#         cols_row[0].write(f"**{index}**")
#         cols_row[1].write(doc.get('nombre', '-'))
#         cols_row[2].write(f"${doc.get('precio', 0):,.2f}")
#         cols_row[3].write(str(doc.get('stock', 0)))
#         cols_row[4].write(doc.get('categoria', '-'))
#         cols_row[5].write(doc.get('descripcion', '-'))
# 
#         ingredientes_raw = doc.get('ingredientes', '—')
#         if isinstance(ingredientes_raw, list):
#           ingredientes_texto = ", ".join(str(i) for i in ingredientes_raw)
#         else:
#           ingredientes_texto = str(ingredientes_raw)
#         cols_row[6].write(ingredientes_texto)
# 
#         cols_row[7].write(doc.get('estado', '-'))
# 
#         sellos_raw = doc.get('sellos', '—')
#         if isinstance(sellos_raw, list):
#           sellos_texto = ", ".join(str(i) for i in sellos_raw)
#         else:
#           sellos_texto = str(sellos_raw)
# 
#         cols_row[8].write(sellos_texto)
# 
#       # Botón eliminar directo usando el _id único de MongoDB como Key
#       # El parámetro 'type="primary"' resalta el botón en rojo/color de énfasis según el tema
#         if cols_row[9].button("❌", key=f"del_{doc['_id']}", help=f"Eliminar permanentemente {doc.get('nombre')}"):
#           menu.delete_one({"_id": doc["_id"]})
#           st.toast(f"Producto '{doc.get('nombre')}' eliminado.", icon="❌")
#           st.rerun()
#     else:
#      st.info("el menu está vacía. Agrega un producto en la siguiente pestaña.")
# 
# with tab_agregar_menu:
# 
#     st.image("agregar_m.png",width=500 )
# 
#     st.header("Registrar Nuevo Producto")
# 
#     with st.form("form_crear"):
#         col1, col2 = st.columns(2)
#         with col1:
#             nuevo_id = st.number_input("ID numérico", min_value=1, step=1, value=73)
#             nuevo_nombre = st.text_input("Nombre del Producto", placeholder="Ej. Del Valle Frut Citrus 600ml")
#             nuevo_precio = st.number_input("Precio ($)", min_value=0.0, step=0.5, value=20.0)
#             nuevo_stock = st.number_input("Stock Inicial", min_value=0, step=1, value=10)
#         with col2:
#             nueva_categoria = st.text_input("Categoría", value="Bebidas")
#             nuevo_ingredientes = st.text_input("Proveedor", value="Del Valle")
#             nueva_descripcion = st.text_area("Descripción", placeholder="Breve descripción...")
#             nuevo_estado = st.text_input("Estado", value="Disponible/No disponible")
# 
#         boton_guardar = st.form_submit_button("Guardar Producto")
#         if boton_guardar:
#             if nuevo_nombre.strip() == "":
#                 st.error("El nombre no puede estar vacío.")
#             else:
#                 nuevo_documento = {
#                     "id": int(nuevo_id),
#                     "nombre": nuevo_nombre,
#                     "precio": nuevo_precio,
#                     "stock": int(nuevo_stock),
#                     "descripcion": nueva_descripcion,
#                     "categoria": nueva_categoria,
#                     "ingredientes": nuevo_ingredientes,
#                     "estado": nuevo_estado
# 
#                 }
#                 menu.insert_one(nuevo_documento)
#                 st.success(f" ¡Producto '{nuevo_nombre}' agregado!")
#                 st.rerun()
# 
# 
# with tab_editar_menu:
#     st.image("editar_m.png",width=500 )
#     st.header("Modificar un Producto Existente")
# 
#     if documentos:
#         opciones_productos = {f"{doc['nombre']} (ID: {doc['id']})": doc for doc in documentos}
#         seleccion = st.selectbox("Selecciona el producto a editar:", opciones_productos.keys())
#         prod_actual = opciones_productos[seleccion]
# 
#         with st.form("form_actualizar"):
#             col1, col2 = st.columns(2)
#             with col1:
#                 edit_nombre = st.text_input("Nombre del Producto", value=prod_actual.get('nombre', ''))
#                 edit_precio = st.number_input("Precio ($)", min_value=0.0, step=0.5, value=float(prod_actual.get('precio', 0)))
#                 edit_stock = st.number_input("Stock", min_value=0, step=1, value=int(prod_actual.get('stock', 0)))
#             with col2:
#                 edit_categoria = st.text_input("Categoría", value=prod_actual.get('categoria', ''))
#                 edit_descripcion = st.text_area("Descripción", value=prod_actual.get('descripcion', ''))
#                 edit_estado = st.text_input("Estado", value=prod_actual.get('estado', ''))
#                 edit_ingredientes = st.text_input("ingredientes", value=prod_actual.get('ingredientes', ''))
# 
#             boton_actualizar = st.form_submit_button("Actualizar Cambios")
#             if boton_actualizar:
#                 menu.update_one(
#                     {"_id": prod_actual["_id"]},
#                     {"$set": {
#                         "nombre": edit_nombre,
#                         "precio": edit_precio,
#                         "stock": int(edit_stock),
#                         "descripcion": edit_descripcion,
#                         "categoria": edit_categoria,
#                         "estado": edit_estado,
#                         "ingredientes": edit_ingredientes
#                     }}
#                 )
#                 st.success("¡Producto actualizado!")
#                 st.rerun()
#     else:
#         st.info("No hay productos disponibles para editar.")
# 
# with tab_eliminar_menu:
#     st.image("eliminar_menu.png",width=500 )
#     st.header("Eliminar un Producto")
#     if documentos:
#         opciones_productos = {f"{doc['nombre']} (ID: {doc['id']})": doc for doc in documentos}
#         seleccion = st.selectbox("Selecciona el producto a eliminar:", opciones_productos.keys())
#         # NOTE: The actual deletion logic for this tab is not yet implemented.
#         # The 'Ver Productos del menu' tab already provides a delete button next to each item.
#         # If you want a separate delete button here, you would add similar logic:
#         if st.button("Eliminar Seleccionado"):
#             menu.delete_one({"_id": opciones_productos[seleccion]["_id"]})
#             st.toast(f"Producto '{opciones_productos[seleccion].get('nombre')}' eliminado.", icon="❌")
#             st.rerun()
# 
# with tab_ver_gatos:
#     st.image("ver_g.png",width=500 )
#     st.header("Listado de gatos")
#     # Obtener documentos actualizados
#     documentos_gatos = list(gatos.find())
#     if documentos_gatos:
#       t_gatos = len(documentos_gatos)
#       col_g1, col_g2 = st.columns(2)
# 
#       col_g1.metric("Total de gatos", t_gatos)
# 
#       # Proporciones para 8 columns: id, nombre, edad, personalidad, preferencia, relacion, horario, estado
#       proporciones = [0.6, 1.5, 0.8, 1, 1.5, 1, 1, 1]
#     # Encabezados de la tabla
# 
#       cols_header = st.columns(proporciones)
#       cols_header[0].markdown("*id*")
#       cols_header[1].markdown("*nombre*")
#       cols_header[2].markdown("*edad*")
#       cols_header[3].markdown("*personalidad*")
#       cols_header[4].markdown("*preferencia*")
#       cols_header[5].markdown("*relacion*")
#       cols_header[6].markdown("*horario*")
#       cols_header[7].markdown("*estado*")
#       st.markdown("<hr style='margin-top:0px; margin-bottom:10px;'>", unsafe_allow_html=True)
# 
#       # Placeholder for displaying cat data - you would add a loop similar to the menu items
#       for index, doc_gato in enumerate(documentos_gatos, start=1):
#           cols_row_gato = st.columns(proporciones)
#           cols_row_gato[0].write(f"**{index}**")
#           cols_row_gato[1].write(doc_gato.get('nombre', '-'))
#           cols_row_gato[2].write(doc_gato.get('edad', '-'))
#           cols_row_gato[3].write(doc_gato.get('personalidad', '-'))
#           cols_row_gato[4].write(doc_gato.get('preferencia', '-'))
#           cols_row_gato[5].write(doc_gato.get('relacion', '-'))
#           cols_row_gato[6].write(doc_gato.get('horario', '-'))
#           cols_row_gato[7].write(doc_gato.get('estado', '-'))
# 
#     else:
#         st.info("No hay gatos registrados.")
# 
# with tab_agregar_gatos:
#     st.image("agregar_g.png",width=500 )
# 
#     st.header("Registrar nuevo gato")
#     with st.form("form_crear_gato"):
#         col1, col2 = st.columns(2)
#         with col1:
#             nuevo_id = st.number_input("ID numérico", min_value=1, step=1, value=73)
#             nuevo_nombre = st.text_input("Nombre del gato", placeholder="Ej. Gato 1")
#             nueva_edad = st.text_input("edad del gato", placeholder= "Ej.2 años")
#             nueva_personalidad = st.text_input("personalidad del gato", placeholder= "Ej.perezoso")
#         with col2:
#             nueva_preferencia = st.text_input("preferencia del gato", placeholder= "Ej.socialismo")
#             nueva_relacion = st.text_input("relacion del gato", placeholder= "Ej.el favorito")
#             nuevo_horario = st.text_input("horario del gato", placeholder= "Ej.12-1pm")
#             nuevo_estado = st.text_input("estado del gato", placeholder= "Ej.disponible")
# 
#         boton_guardar = st.form_submit_button("Guardar gato")
#         if boton_guardar:
#             if nuevo_nombre.strip() == "":
#                 st.error("El nombre no puede estar vacío.")
#             else:
#                 nuevo_documento = {
#                     "id": int(nuevo_id),
#                     "nombre": nuevo_nombre,
#                     "edad": nueva_edad,
#                     "personalidad": nueva_personalidad,
#                     "preferencia": nueva_preferencia,
#                     "relacion": nueva_relacion,
#                     "horario": nuevo_horario,
#                     "estado": nuevo_estado
# 
#                 }
#                 gatos.insert_one(nuevo_documento)
#                 st.success(f" ¡Gato '{nuevo_nombre}' agregado!")
#                 st.rerun()
# 
# with tab_rankig_clientes:
#     st.image("clientes.png",width=500 )
# 
#     st.header("Los mejores clientes")
#     def obtener_ranking_clientes(limite=5):
#      cursor = clientes.find(
#          {},
#         {"_id": 0, "nombre": 1, "apellido":1, "puntos": 1} # Traemos solo nombre y puntos
#      ).sort("puntos", -1).limit(limite)
# 
#      return list(cursor)
# 
#     top_n = st.slider("Cantidad de clientes a mostrar:", min_value=3, max_value=15, value=5)
#     datos_ranking = obtener_ranking_clientes(top_n)
# 
#     if datos_ranking:
#      df = pd.DataFrame(datos_ranking)
#      df = df.iloc[::-1]
#      st.bar_chart(
#         df,
#         x="nombre",
#         y="puntos",
#         color="#FF4B4B",
#         horizontal=True
#     )
#      cliente_top = datos_ranking[0]
#      st.toast(f"🏆 {cliente_top['nombre']} va liderando con {cliente_top['puntos']} puntos.")
#     else:
#         st.info("No hay clientes registrados.")
# 
# with tab_editar_cliente:
#   st.image("editar_c.png",width=500 )
#   # Obtener documentos de clientes para el selector
#   documentos_clientes = list(clientes.find())
# 
#   if documentos_clientes:
#     # Crear un diccionario para mapear el nombre del cliente a su documento completo
#     opciones_clientes = {f"{doc.get('nombre', '')} {doc.get('apellido', '')} (ID: {doc.get('id', '')})": doc for doc in documentos_clientes}
# 
#     # Selector para elegir el cliente a editar
#     seleccion = st.selectbox("Selecciona el cliente a editar:", opciones_clientes.keys())
# 
#     if seleccion:
#       cliente_actual = opciones_clientes[seleccion]
# 
#       with st.form("form_actualizar_cliente"):
#         st.write(f"Editando cliente: **{cliente_actual.get('nombre', '')} {cliente_actual.get('apellido', '')}**")
#         edit_nombre = st.text_input("Nombre del Cliente", value=cliente_actual.get('nombre', ''))
#         edit_apellido = st.text_input("Apellido del Cliente", value=cliente_actual.get('apellido', ''))
#         edit_direccion = st.text_input("Dirección del Cliente", value=cliente_actual.get('direccion', ''))
#         edit_telefono = st.text_input("Teléfono del Cliente", value=cliente_actual.get('telefono', ''))
#         edit_email = st.text_input("Email del Cliente", value=cliente_actual.get('email', ''))
#         edit_puntos = st.number_input("Puntos", min_value=0, step=1, value=int(cliente_actual.get('puntos', 0)))
# 
#         boton_actualizar = st.form_submit_button("Actualizar Cambios")
#         if boton_actualizar:
#           clientes.update_one(
#             {"_id": cliente_actual["_id"]},
#             {"$set": {
#               "nombre": edit_nombre,
#               "apellido": edit_apellido,
#               "direccion": edit_direccion,
#               "telefono": edit_telefono,
#               "email": edit_email,
#               "puntos": int(edit_puntos)
#             }}
#           )
#           st.success("¡Cliente actualizado!")
#           st.rerun()
#   else:
#     st.info("No hay clientes registrados para editar.")
# 
# with tab_agregar_cliente:
#     st.image("agregar_c.png",width=500 )
# 
#     with st.form("form_crear_cliente"):
#         col1, col2 = st.columns(2)
#         with col1:
#             nuevo_id_cliente = st.number_input("ID numérico Cliente", min_value=1, step=1, value=101)
#             nuevo_nombre_cliente = st.text_input("Nombre del Cliente", placeholder="Ej. Juan")
#             nuevo_apellido_cliente = st.text_input("Apellido del Cliente", placeholder="Ej. Pérez")
#             nuevo_telefono_cliente = st.text_input("Teléfono del Cliente", placeholder="Ej. 123-456-7890")
#         with col2:
#             nuevo_direccion_cliente = st.text_area("Dirección del Cliente", placeholder="Ej. Calle Falsa 123")
#             nuevo_email_cliente = st.text_input("Email del Cliente", placeholder="Ej. juan.perez@example.com")
#             nuevo_puntos_cliente = st.number_input("Puntos Iniciales", min_value=0, step=1, value=0)
# 
#         boton_guardar_cliente = st.form_submit_button("Guardar Cliente")
#         if boton_guardar_cliente:
#             if nuevo_nombre_cliente.strip() == "":
#                 st.error("El nombre del cliente no puede estar vacío.")
#             else:
#                 nuevo_documento_cliente = {
#                     "id": int(nuevo_id_cliente),
#                     "nombre": nuevo_nombre_cliente,
#                     "apellido": nuevo_apellido_cliente,
#                     "direccion": nuevo_direccion_cliente,
#                     "telefono": nuevo_telefono_cliente,
#                     "email": nuevo_email_cliente,
#                     "puntos": int(nuevo_puntos_cliente)
#                 }
#                 clientes.insert_one(nuevo_documento_cliente)
#                 st.success(f" ¡Cliente '{nuevo_nombre_cliente} {nuevo_apellido_cliente}' agregado!")
#                 st.rerun()